AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  list:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-list
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: list
      CodeUri: src/list
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref notesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref notesTable
          TABLE_ARN: !GetAtt notesTable.Arn
      Events:
        HttpApiGETnote:
          Type: HttpApi
          Properties:
            Path: /note
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  create:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: create
      CodeUri: src/create
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref notesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref notesTable
          TABLE_ARN: !GetAtt notesTable.Arn
      Events:
        HttpApiPOSTnote:
          Type: HttpApi
          Properties:
            Path: /note
            Method: POST
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  notesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-notesTable
  get:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: get
      CodeUri: src/get
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref notesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref notesTable
          TABLE_ARN: !GetAtt notesTable.Arn
      Events:
        HttpApiGETnoteid:
          Type: HttpApi
          Properties:
            Path: /note/{id}
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  update:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-update
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: update
      CodeUri: src/update
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref notesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref notesTable
          TABLE_ARN: !GetAtt notesTable.Arn
      Events:
        HttpApiPUTnoteid:
          Type: HttpApi
          Properties:
            Path: /note/{id}
            Method: PUT
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  remove:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-remove
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: remove
      CodeUri: src/remove
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref notesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref notesTable
          TABLE_ARN: !GetAtt notesTable.Arn
      Events:
        HttpApiDELETEnoteid:
          Type: HttpApi
          Properties:
            Path: /note/{id}
            Method: DELETE
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
          version: '1.0'
        paths:
          /note:
            get:
              responses: {}
            post:
              responses: {}
          /note/{id}:
            put:
              responses: {}
            delete:
              responses: {}
            get:
              responses: {}
      FailOnWarnings: true
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name
  EnvironmentTagName:
    Type: String
    Description: Environment Name
